import Head from 'next/head';

export const metadata = {
  title: 'Create Next App', 
  description: 'Generated by create next app',
};

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title> {}
      </Head>
      {children}
    </div>
  );
};

export default Layout;
